Bug fix/#4062/#4063/section names in edit table differences from mockup
ita-social-projects/GreenCityClient pull request #1599
Opened 2022-05-09 17:56 UTC by YevhenSalamakha

2022-05-09 19:54 UTC, NewArtMask requested changes

2022-05-09 19:54 UTC, NewArtMask commented on src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table.component.scss
> +    color: #000;
Use please variable from ubs file: --ubs-primary-black: #000;

2022-05-15 19:19 UTC, hnativlyubomyr approved these changes

2022-05-16 05:58 UTC, NewArtMask approved these changes

2022-05-16 06:27 UTC, Mukola1983 approved these changes

2022-05-16 06:27 UTC, krayevska approved these changes

2022-05-16 06:28 UTC, melnychenkoas approved these changes

2022-05-16 06:28 UTC, merged