fixed bug with text wasn't on centr
ita-social-projects/GreenCityClient pull request #1698
Opened 2022-06-23 08:42 UTC by YevhenSalamakha

Result berofe: The text in the button is aligned to the left.
Actual result: The text in the button is aligned to the center.

2022-06-23 08:46 UTC, veronnah approved these changes

2022-06-23 10:21 UTC, Myh45 approved these changes

2022-06-23 12:14 UTC, NewArtMask commented on src/app/shared/header/header.component.scss
> -  width: 70px;
Don't match mockup dimensions.

![image](https://user-images.githubusercontent.com/34275837/175296149-db3d6212-1270-4af2-9827-a32569788723.png)


https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=21754%3A74151

2022-07-04 06:14 UTC, voronkooleksandr approved these changes

2022-07-15 10:11 UTC, melnychenkoas approved these changes

2022-07-15 11:26 UTC, NewArtMask requested changes

2022-07-15 11:26 UTC, NewArtMask commented on src/app/shared/header/header.component.scss
> +  padding: 8px 30px;
![image](https://user-images.githubusercontent.com/34275837/179214340-94695a2a-e17d-4a59-b99c-171e0f0b8fa6.png)

2022-07-24 20:27 UTC, NewArtMask approved these changes

2022-07-25 06:07 UTC, merged