fixed bug with wrong display of fields name
ita-social-projects/GreenCityClient pull request #1728
Opened 2022-07-04 13:27 UTC by YevhenSalamakha

2022-07-04 14:39 UTC, NewArtMask requested changes

2022-07-04 14:39 UTC, NewArtMask commented on src/app/ubs/ubs-admin/components/ubs-admin-table/workspace.code-workspace
> +  "folders": [],
Remove this workspace folder!

2022-07-24 17:41 UTC, NewArtMask approved these changes

2022-07-25 06:05 UTC, voronkooleksandr approved these changes

2022-07-25 06:09 UTC, merged