bugfix/#4164/The_error_messages_are_absent_for_'Phone'_field_when_Admin_enters_invalid_values_on_'Information_about_client'_page
ita-social-projects/GreenCityClient pull request #1815
Opened 2022-09-08 10:24 UTC by SokhaTaras

2022-09-10 12:16 UTC, zaitsev-oleksii reviewed
1. I suggest using `app/shared/ubs-input-error` component to display error: onChanges will trigger on component input changes, functions in template - on every detection change;
2. Use `app/shared/phone-validator` instead of `pattern validator`

2022-09-10 14:56 UTC, zaitsev-oleksii requested changes
Change validators for `recipientPhoneNumber` in `ubs/ubs-admin/components/ubs-admin-order.component`: `Validators.pattern(Patterns.adminPhone)` -> `PhoneNumberValidator('UA')`;
If there is a need for `wrong number length` error message,  create custom validator for it.

2022-09-10 14:56 UTC, zaitsev-oleksii commented on src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
> +
```suggestion
```

2022-09-10 14:56 UTC, zaitsev-oleksii commented on src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.html
> +          </div>
```suggestion
          <div *ngIf="userInfoDto.controls['recipientPhoneNumber'].invalid && userInfoDto.controls['recipientPhoneNumber'].touched">
            <div class="error-message">
              <app-ubs-input-error
                [formElement]="userInfoDto.controls['recipientPhoneNumber']"
                [phoneNumberFieldValue]="userInfoDto.controls['recipientPhoneNumber'].value"
              ></app-ubs-input-error>
            </div>
          </div>
```

2022-09-10 14:56 UTC, zaitsev-oleksii commented on src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.ts
> +import { FormGroup, AbstractControl } from '@angular/forms';
```suggestion
import { FormGroup } from '@angular/forms';
```

2022-09-10 15:38 UTC, SokhaTaras commented on src/app/ubs/ubs-admin/components/ubs-admin-order-client-info/ubs-admin-order-client-info.component.html
> +          </div>
You have good suggestions, but, I guess they all are out of scope of this task.

2022-09-12 06:26 UTC, marianaharnyk approved these changes

2022-09-12 06:26 UTC, NewArtMask approved these changes

2022-09-12 06:26 UTC, hnativlyubomyr approved these changes

2022-09-12 06:29 UTC, zaitsev-oleksii approved these changes

2022-09-12 06:29 UTC, voronkooleksandr approved these changes

2022-09-12 06:30 UTC, merged