Bugfix/#4609 upload image size validation create news
ita-social-projects/GreenCityClient pull request #1876
Opened 2022-10-04 12:58 UTC by atsa21

System doesn’t allow to add JPEG image more than 10 Mb

2022-10-04 14:39 UTC, zaitsev-oleksii requested changes

2022-10-04 14:39 UTC, zaitsev-oleksii commented on src/app/main/component/shared/components/drag-and-drop/drag-and-drop.component.ts
> +      const imageValCondition = (item.file.type === 'image/jpeg' || item.file.type === 'image/png') && item.file.size < 10000000;
```suggestion
      const imageValCondition = (item.file.type === 'image/jpeg' || item.file.type === 'image/png') && item.file.size < 10485760;
```

2022-10-04 16:49 UTC, zaitsev-oleksii approved these changes

2022-10-04 17:25 UTC, vitaliitrehubov approved these changes

2022-10-04 19:51 UTC, vplvua approved these changes

2022-10-09 17:57 UTC, hnativlyubomyr approved these changes

2022-10-11 11:37 UTC, marianaharnyk approved these changes

2022-10-13 19:38 UTC, merged