Bugfix#4771/Displaying of extended tariff card
ita-social-projects/GreenCityClient pull request #1983
Opened 2022-12-03 17:53 UTC by marianaharnyk

2022-12-04 11:31 UTC, zaitsev-oleksii requested changes

2022-12-04 11:31 UTC, zaitsev-oleksii commented on src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
> +      <td class="last-col" *ngIf="selectedCard.tariff != 'Неактивно'" [matMenuTriggerFor]="crumbs">
It's not good to use translation in if statement. You should use either enum or a specific key. Also replace != with !==.

2022-12-04 11:31 UTC, zaitsev-oleksii commented on src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
> +      <td class="last-col" *ngIf="selectedCard.tariff === 'Неактивно'" [matMenuTriggerFor]="restore">
Same here.

2022-12-04 13:42 UTC, marianaharnyk commented on src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-dashboard.component.html
> +      <td class="last-col" *ngIf="selectedCard.tariff === 'Неактивно'" [matMenuTriggerFor]="restore">
Yes, thanks

2022-12-04 17:13 UTC, zaitsev-oleksii approved these changes

2022-12-04 17:38 UTC, hnativlyubomyr approved these changes

2022-12-04 17:39 UTC, katia9261 approved these changes

2022-12-05 07:40 UTC, SokhaTaras approved these changes

2022-12-05 07:40 UTC, atsa21 approved these changes

2022-12-05 07:42 UTC, hnativlyubomyr approved these changes

2022-12-05 07:42 UTC, merged