Text alignment5171
ita-social-projects/GreenCityClient pull request #2158
Opened 2023-02-16 13:11 UTC by KKatiaa

Corrected Text Alignment for 'Region' and 'District' comboboxes in the 'Waste export address' section in the Admin Cabinet #5171

2023-02-16 13:20 UTC, SokhaTaras requested changes
You have to revert package-lock.json

2023-02-16 15:12 UTC, SokhaTaras approved these changes

2023-02-16 15:12 UTC, katia9261 commented on src/app/ubs/ubs-user/ubs-user-order-details/ubs-user-order-details.component.html
> +    <div *ng-If="order.orderComment !== ''">
replace it with "*ngIf"

2023-02-16 20:44 UTC, atsa21 approved these changes

2023-02-19 12:31 UTC, hnativlyubomyr approved these changes

2023-02-21 07:31 UTC, marianaharnyk approved these changes

2023-02-21 07:32 UTC, NadiiaStoiko approved these changes

2023-02-21 07:32 UTC, merged