Bugfix/#5533-added-services
ita-social-projects/GreenCityClient pull request #2281
Opened 2023-03-28 11:23 UTC by KKatiaa

#5533 Change request to US #4427, #4428 "Add a service "Сервіс" to the pricing card", "Edit a service "Сервіс" in the pricing card"
https://github.com/ita-social-projects/GreenCity/issues/5533

2023-03-28 11:47 UTC, katia9261 requested changes

2023-03-28 11:47 UTC, katia9261 commented on src/app/ubs/ubs/services/order.service.ts
> +import { serializeNodes } from '@angular/compiler/src/i18n/digest';
Where do we use this import?

2023-03-28 11:47 UTC, katia9261 commented on src/app/ubs/ubs/services/order.service.ts
> +  saveServiceName(serviceName: string): void {
Where do we use these functions and is there any reason to redeclare them?

2023-03-29 17:23 UTC, atsa21 commented on src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.ts
> +    return this.addServiceForm.get(control);
Add type of function return :AbstractControl

2023-03-29 17:27 UTC, atsa21 commented on src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-pricing-page/ubs-admin-tariffs-add-service-pop-up/ubs-admin-tariffs-add-service-pop-up.component.html
> +          {{ 'ubs-tariffs-add-service.error_service_field_message' | translate }}
Use **app-ubs-input-error** for ubs error messages
For example we use it in **UBSAddAddressPopUpComponent**

2023-04-03 06:25 UTC, closed without merging