bugfix/#5208
ita-social-projects/GreenCityClient pull request #2515
Opened 2023-06-16 14:27 UTC by Tadei-Mykola

The error has been fixed where adding another order number was causing it to be highlighted in red.

2023-06-17 06:27 UTC, katia9261 requested changes
you pushed deleted package-lock.json, so you need to run `git checkout origin/dev  package-lock.json` on your current branch 
It will delete the changes in this file, but it will not delete all the changes in the commit

2023-06-18 10:46 UTC, hnativlyubomyr commented on src/app/ubs/ubs-admin/components/ubs-admin-order-details-form/ubs-admin-order-details-form.component.ts
> +    return value.length === 0;
return !value.trim().length

2023-06-19 06:22 UTC, katia9261 approved these changes

2023-06-26 06:12 UTC, ruslan-teh approved these changes

2023-06-26 06:12 UTC, hnativlyubomyr approved these changes

2023-06-26 06:12 UTC, KKatiaa approved these changes

2023-06-26 06:12 UTC, OksanaFilipchuk approved these changes

2023-06-26 06:12 UTC, AlexW8719 approved these changes

2023-06-26 06:12 UTC, mdashko approved these changes

2023-06-26 06:12 UTC, merged