Bugfix/#5807 certificate in the actual amount
ita-social-projects/GreenCityClient pull request #2525
Opened 2023-06-19 06:16 UTC by mdashko

2023-06-19 06:46 UTC, katia9261 requested changes
you pushed deleted package-lock.json, so you need to run git checkout origin/dev  package-lock.json on your current branch
It will delete the changes in this file, but it will not delete all the changes in the commit

2023-06-26 06:12 UTC, KKatiaa approved these changes

2023-06-26 06:23 UTC, ruslan-teh approved these changes

2023-06-26 06:23 UTC, hnativlyubomyr approved these changes

2023-06-26 06:23 UTC, Tadei-Mykola approved these changes

2023-06-26 06:23 UTC, OksanaFilipchuk approved these changes

2023-06-26 06:23 UTC, AlexW8719 approved these changes

2023-06-26 06:24 UTC, merged