Bugfix/#5136/an authorized user cannot change the order of pictures in the created event
ita-social-projects/GreenCityClient pull request #2640
Opened 2023-08-17 13:27 UTC by sobkiv

Made the possibility for an authorized user to change photos order with drag-and-drop functionality in the created Event

2023-08-17 18:15 UTC, NadiiaStoiko approved these changes

2023-08-17 18:19 UTC, katia9261 requested changes
Please, run `git checkout origin/dev  package-lock.json` to revert changes in package-lock.json

2023-08-18 08:42 UTC, katia9261 approved these changes

2023-08-20 12:51 UTC, hnativlyubomyr approved these changes

2023-08-21 06:11 UTC, KKatiaa approved these changes

2023-08-21 06:19 UTC, mdashko approved these changes

2023-08-21 06:19 UTC, OksanaFilipchuk approved these changes

2023-08-21 06:19 UTC, Tadei-Mykola approved these changes

2023-08-21 06:20 UTC, merged