bugfix/#6248
ita-social-projects/GreenCityClient pull request #2674
Opened 2023-09-08 11:16 UTC by KKatiaa

2023-09-10 08:19 UTC, hnativlyubomyr approved these changes

2023-09-11 06:09 UTC, sobkiv approved these changes

2023-09-15 11:19 UTC, Tadei-Mykola approved these changes

2023-09-16 10:45 UTC, sobkiv requested changes
Please, run `git checkout origin/dev  package-lock.json` to revert changes in package-lock.json

2023-09-25 06:19 UTC, Tadei-Mykola approved these changes

2023-09-25 06:19 UTC, NadiiaStoiko approved these changes

2023-09-25 06:21 UTC, hnativlyubomyr approved these changes

2023-09-25 06:21 UTC, sobkiv approved these changes

2023-09-25 06:23 UTC, merged