[Bug Fix #2137, #1886, #2152]
ita-social-projects/GreenCityClient pull request #721
Opened 2021-01-13 14:28 UTC by ZooMingGG

ita-social-projects/GreenCity#2137
Changed default number of news from 6 to 12
Previous:
![103314982-f424c900-4a2c-11eb-812c-2eb88a969aa5](https://user-images.githubusercontent.com/55454496/104464299-724fa680-55bb-11eb-87ef-5abdecda7fc9.png)
Result:
![image](https://user-images.githubusercontent.com/55454496/104464380-8693a380-55bb-11eb-8c1f-334c05a806ed.png)
ita-social-projects/GreenCity#1886
Fixed incorrect text alignment in content item on the Eco News page
Previous:
![99727452-a7121680-2ac0-11eb-8d1f-23e6749a5f1c](https://user-images.githubusercontent.com/55454496/104464915-23564100-55bc-11eb-86ad-f809cb831749.jpg)
Result:
![image](https://user-images.githubusercontent.com/55454496/104465001-408b0f80-55bc-11eb-8192-1ff9f50077a1.png)
ita-social-projects/GreenCity#2152
Changed Eco News page structure for better accessibility

2021-01-13 15:12 UTC, yuriiLisunov approved these changes

2021-01-13 15:23 UTC, luchward requested changes
1. Use sensible titles for pull requests.
2. Make corresponding screenshots of previous and actual page view (the same dimensions, positions, resolutions).

2021-01-13 17:31 UTC, idzhersh approved these changes

2021-01-13 17:31 UTC, luchward approved these changes

2021-01-14 07:12 UTC, KirillAbramo approved these changes

2021-01-18 17:16 UTC, mr-pavlenko approved these changes

2021-01-18 17:16 UTC, merged