changed post-news-loader values in languages json files
ita-social-projects/GreenCityClient pull request #780
Opened 2021-03-25 21:59 UTC by idzhersh

2021-03-29 20:18 UTC, JimHolman1199 commented
Could you please add description to PR and Change branch name as we discussed ?

2021-03-29 20:20 UTC, JimHolman1199 requested changes
Add desc to PR
change branch name

2021-04-01 17:10 UTC, idzhersh commented
> Could you please add description to PR and Change branch name as we discussed ?

Done

2021-04-01 21:34 UTC, VitalyBorysenko approved these changes

2021-04-02 07:32 UTC, yuriiLisunov approved these changes

2021-04-02 09:07 UTC, paslavskyi9roman approved these changes

2021-04-02 09:47 UTC, closed without merging