bugfix/2528 - [Habits] Change /habit/assign/allForCurrentUser to /habit/assign controler
ita-social-projects/GreenCityClient pull request #790
Opened 2021-04-01 12:17 UTC by idzhersh

changed link in getAssignedHabits method

2021-04-01 20:07 UTC, JimHolman1199 commented
Changes in file package-lock.json  should not be here.

2021-04-01 20:07 UTC, JimHolman1199 requested changes

2021-04-01 20:07 UTC, JimHolman1199 commented on src/app/service/habit-assign/habit-assign.service.ts
> +    return this.http.get<Array<HabitAssignInterface>>(`${habitAssignLink}/allForCurrentUser?lang=${this.language}`);
CHANGE branch name, as we agreed!

2021-04-01 20:08 UTC, JimHolman1199 commented on src/app/service/habit-assign/habit-assign.service.ts
> +    return this.http.get<Array<HabitAssignInterface>>(`${habitAssignLink}/allForCurrentUser?lang=${this.language}`);
remove from package-lock.json

2021-04-01 20:31 UTC, VitalyBorysenko approved these changes

2021-04-02 07:30 UTC, yuriiLisunov approved these changes

2021-04-02 08:44 UTC, closed without merging