[Edit profile] User is not redirected to the 'My habits' page after editing personal info and clicking the 'Save' button #2629
ita-social-projects/GreenCityClient pull request #848
Opened 2021-05-03 13:53 UTC by SofiiaBaziv

**Before**
The user is not redirected after save

**After**
The user is redirected to 'My habits' page after save

2021-05-04 08:23 UTC, JimHolman1199 commented
please rename branch name to have more context, instead  of bugfix/#2629 to be bugfix/#2629-some-cool-desc  format

2021-05-04 08:23 UTC, JimHolman1199 requested changes
Change branch name

2021-05-04 08:23 UTC, JimHolman1199 commented on src/app/component/user/services/edit-profile.service.ts
> +    return this.http.put<EditProfileModel>(`${mainUserLink}user/profile`, data, { ...this.httpOptions, responseType: 'text' as 'json'});
nice catch

2021-05-05 07:30 UTC, yuriiLisunov approved these changes

2021-05-06 13:26 UTC, Edw1x approved these changes

2021-05-08 09:43 UTC, JimHolman1199 approved these changes

2021-05-08 10:43 UTC, AlekOK approved these changes

2021-05-08 10:51 UTC, paslavskyi9roman approved these changes

2021-05-08 12:33 UTC, merged