[Create news] User can published news with empty fields, after click on button 'Preview' #2653
ita-social-projects/GreenCityClient pull request #849
Opened 2021-05-03 16:16 UTC by SofiiaBaziv

**Before**
Button 'Publish' is enabled. After click on 'Publish' button, opens new page(as on mock up). In result all buttons on page do not respond to clicks.

**After**
Button 'Publish' is disabled. User can`t published news.

2021-05-04 18:33 UTC, idzhersh approved these changes

2021-05-04 20:31 UTC, JimHolman1199 requested changes
change branch name to follow our pattern

2021-05-05 07:31 UTC, yuriiLisunov approved these changes

2021-05-05 20:00 UTC, Edw1x approved these changes

2021-05-08 09:44 UTC, JimHolman1199 approved these changes

2021-05-08 10:42 UTC, AlekOK approved these changes

2021-05-08 10:52 UTC, paslavskyi9roman approved these changes

2021-05-08 10:52 UTC, paslavskyi9roman approved these changes

2021-05-08 12:32 UTC, merged