[Forgot password] The 'or sign in with' text is shown insted of the 'or' text #2685
ita-social-projects/GreenCityClient pull request #892
Opened 2021-05-20 18:00 UTC by SofiiaBaziv

**Before**
The 'or sign in with' text is shown between two buttons
![bug1](https://user-images.githubusercontent.com/79053863/116275342-374d3980-a78c-11eb-9653-99212483d487.png)

**After**
The 'or' text is shown between two buttons
![bug1](https://user-images.githubusercontent.com/79053863/116275518-6499e780-a78c-11eb-8239-65e46208b2f9.png)

2021-05-21 08:04 UTC, yuriiLisunov approved these changes

2021-05-21 19:32 UTC, idzhersh approved these changes

2021-05-22 15:09 UTC, paslavskyi9roman approved these changes

2021-05-23 11:56 UTC, JimHolman1199 requested changes

2021-05-23 11:56 UTC, JimHolman1199 commented on src/assets/i18n/en.json
> +        "or-signin": "or",
we already have OR at line 351, let's use that one

2021-05-24 15:45 UTC, Edw1x approved these changes

2021-05-26 06:16 UTC, JimHolman1199 approved these changes

2021-05-26 06:16 UTC, merged