Bugfix/#2807 unit test
ita-social-projects/GreenCityClient pull request #910
Opened 2021-05-31 16:16 UTC by oliachipko

2021-06-01 16:23 UTC, andreikazmirovich requested changes

2021-06-01 16:23 UTC, andreikazmirovich commented on src/app/main/component/eco-news/components/create-edit-news/create-edit-news.component.ts
> +    public snackBar: MatSnackBarComponent,
Why did you change it to public?
Was it Prettier?

2021-06-02 13:06 UTC, andreikazmirovich approved these changes

2021-06-08 16:39 UTC, JimHolman1199 approved these changes

2021-06-08 16:40 UTC, merged